version: '1.0.0'

services:
  tag-server:
    image: api-monitoring:latest
    container_name: api-monitoring
    build:
      context: .
      args:
        SERVE_PORT: 5000
    ports:
      - "80:5000"
    volumes:
      - ./data:/mnt/data